/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package studentp;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Admin
 */
public class studen extends javax.swing.JFrame {

    /**
     * Creates new form studen
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    PreparedStatement pst1=null;
    ResultSet rs1=null;
    public int p1;
    public int p2;
    
    
    public studen() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        cb = new javax.swing.JComboBox<>();
        panel3 = new java.awt.Panel();
        button1 = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        search_txt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT MONTH");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Company Name");

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CHECK ELIGIBLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Username");

        uname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uname, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March\t", "April", "May", "June", "July\t", "August", "September", "October", "November", "December\t" }));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        button1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button1.setForeground(new java.awt.Color(0, 0, 204));
        button1.setLabel("PROFILE");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Company Eligibilty");
        jLabel2.setOpaque(true);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("LOGOUT");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Company Name", "Job Profile", "Date", "Salary", "Month"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        search_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 0));
        jButton4.setText("REFRESH");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 51, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Placed Student");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        profile p= new profile();
        p.setVisible(true);
        
      this.dispose(); 
        
    }//GEN-LAST:event_button1ActionPerformed

    private void month_boxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_month_boxMouseClicked
        
    }//GEN-LAST:event_month_boxMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         String add3 = null;
          String add4=null;
          String add5=null;
           String a1=null;
          String a3=null;
           String a2=null;
                                                      
        
       // con=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");  
       String cmp=search.getText();
       String user=uname.getText();
        String sql="SELECT 10th,12th,engg_aggregate FROM admin_table where company_name=?";
         String sql1="SELECT ten,twelve,engg FROM student where username=?";
      
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
            pst=con.prepareStatement(sql);
            pst.setString(1,cmp);
            
            rs=pst.executeQuery();
            if(rs.next())
            {
           
            add3=rs.getString("10th");
            
            add4=rs.getString("12th");
            //twelve_txt.setText(add4);

            add5=rs.getString("engg_aggregate");
            //engg_txt.setText(add5);
            
          // JOptionPane.showMessageDialog(null, add3);
            
            
            
                     

            }
            
            pst1=con.prepareStatement(sql1);
            pst1.setString(1,user);
             rs1=pst1.executeQuery();
             
            if(rs1.next())
            {
                a1=rs1.getString("ten");
                a2=rs1.getString("twelve");
                a3=rs1.getString("engg");
               
                
            }
            
                 
            if(Integer.parseInt(a1)>=Integer.parseInt(add3) && Integer.parseInt(a2)>=Integer.parseInt(add4) && Integer.parseInt(a3)>=Integer.parseInt(add5)){
                JOptionPane.showMessageDialog(null, "YOU ARE ELIGIBLE");
            
            } else {
                JOptionPane.showMessageDialog(null, "YOU ARE NOT ELIGIBLE");
           }
          
        }catch(HeadlessException | SQLException e)
        {
               JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String query3="SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table where company_name=?";
        
        try{
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
            pst=con.prepareStatement(query3);
            pst.setString(1,search_txt.getText());
            rs=pst.executeQuery();
            
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                      
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        lofin lg=new lofin();
        lg.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        showTableData();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
       int s;
        s=cb.getSelectedIndex();
         // JOptionPane.showMessageDialog(null, s
         switch (s) {
             case 0:
                 String sql = "SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table WHERE month LIKE 'january'";
                 try{
                     
                     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
                     pst=con.prepareStatement(sql);
                     rs = pst.executeQuery();
           
                     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                     
                 }catch(SQLException e){}
                
                 break;
             case 1:
                 
                  String sql1 = "SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table WHERE month LIKE 'february'";
                 try{
                     
                     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
                     pst=con.prepareStatement(sql1);
                     rs = pst.executeQuery();
           
                     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                     
                 }catch(SQLException e){}
                 
                 break;
             case 2:
                 
                 String sql2 = "SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table WHERE month LIKE 'march'";
                 try{
                     
                     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
                     pst=con.prepareStatement(sql2);
                     rs = pst.executeQuery();
           
                     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                     
                 }catch(SQLException e){}
                 
                 break;
             
             case 3:
                 String sql3 = "SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table WHERE month LIKE 'april'";
                 try{
                     
                     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
                     pst=con.prepareStatement(sql3);
                     rs = pst.executeQuery();
           
                     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                     
                 }catch(SQLException e){}
                 
                 break;
             
             case 4:
                 String sql4 = "SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table WHERE month LIKE 'may'";
                 try{
                     
                     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
                     pst=con.prepareStatement(sql4);
                     rs = pst.executeQuery();
           
                     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                     
                 }catch(SQLException e){}
                 
                 break;
                 
             case 5:
                 String sql5 = "SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table WHERE month LIKE 'june'";
                 try{
                     
                     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
                     pst=con.prepareStatement(sql5);
                     rs = pst.executeQuery();
           
                     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                     
                 }catch(SQLException e){}
                 
                 break;
                 
             case 6:
                 String sql6 = "SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table WHERE month LIKE 'july'";
                 try{
                     
                     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
                     pst=con.prepareStatement(sql6);
                     rs = pst.executeQuery();
           
                     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                     
                 }catch(SQLException e){}
                 
                 break;
                 
             case 7:
                 String sql7 = "SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table WHERE month LIKE 'august'";
                 try{
                     
                     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
                     pst=con.prepareStatement(sql7);
                     rs = pst.executeQuery();
           
                     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                     
                 }catch(SQLException e){}
                 
                 break;
                 
             case 8:
                 String sql8 = "SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table WHERE month LIKE 'september'";
                 try{
                     
                     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
                     pst=con.prepareStatement(sql8);
                     rs = pst.executeQuery();
           
                     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                     
                 }catch(SQLException e){}
                 
                 break;
                 
             case 9:
                 String sql9 = "SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table WHERE month LIKE 'october'";
                 try{
                     
                     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
                     pst=con.prepareStatement(sql9);
                     rs = pst.executeQuery();
           
                     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                     
                 }catch(SQLException e){}
                 
                 break;
                 
             case 10:
                 String sql10 = "SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table WHERE month LIKE 'november'";
                 try{
                     
                     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
                     pst=con.prepareStatement(sql10);
                     rs = pst.executeQuery();
           
                     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                     
                 }catch(SQLException e){}
                 
                 break;
                 
             case 11:
                 String sql11 = "SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table WHERE month LIKE 'december'";
                 try{
                     
                     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
                     pst=con.prepareStatement(sql11);
                     rs = pst.executeQuery();
           
                     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                     
                 }catch(SQLException e){}
                 
                 break;
                
                               
             default:
                 break;
         }
    }//GEN-LAST:event_cbActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        placed_stud ps=new placed_stud();
        ps.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    public void showTableData()
    {
        String query4="SELECT `id`,`company_name`,`job_profile`,`date1`,`salary`,`month` FROM admin_table ";

        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","root");
            pst=con.prepareStatement(query4);
            rs=pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel3;
    private javax.swing.JTextField search;
    private javax.swing.JTextField search_txt;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private lofin setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
}
